site_name: High School Computer Science
site_description: A Space to learn Computer Science in byte-sized lessons for high-school students
site_author: Anshul Yadav
site_url: https://deepsai8.github.io/hscs
repo_url: https://github.com/deepsai8/hscs

copyright: "Copyright &copy; 2024 Anshul Yadav"

theme:
  name: material
  extensions:
      - emoji
  palette:
      - media: "(prefers-color-scheme)"
        toggle:
            icon: material/brightness-auto
            name: Switch to light mode
      - media: "(prefers-color-scheme: light)"
        accent: blue
        primary: blue
        scheme: default
        toggle:
            icon: material/weather-sunny
            name: Switch to dark mode
      - media: "(prefers-color-scheme: dark)"
        accent: blue
        primary: blue
        scheme: slate
        toggle:
            icon: material/weather-night
            name: Switch to light mode
  # palette:
  #   - scheme: default
  #     primary: blue
  #     accent: indigo
  #     toggle:
  #       icon: material/toggle-switch-off-outline
  #       name: Switch to dark mode
  #   - scheme: slate
  #     primary: indigo
  #     accent: indigo
  #     toggle:
  #       icon: material/toggle-switch
  #       name: Switch to light mode
  icon:
    repo: fontawesome/brands/github
  font:
    text: Google Sans
    code: Regular
  features:
    # - navigation.indexes
    # - navigation.sections
    # - navigation.tabs
    # - navigation.top
    # - navigation.tracking
    # - search.highlight
    # - search.share
    # - search.suggest
    # - toc.follow

    - navigation.instant
    - navigation.tracking
    - navigation.top
    # - search.highlight
    - search.share
    - search.suggest
    - content.code.copy

    
extra_css:
  - stylesheets/extra.css


extra_javascript:
  - javascripts/extra.js
  - javascripts/feedback.js
  - javascripts/mathjax.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

extra:
  analytics:
    provider: google
    property: G-1FM49NNNNZ
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-neutral-outline
          name: This page was just okay
          data: 3
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 5
          note: >- 
            Thanks for your feedback!
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/deepsai8
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/deepaksingh8819


plugins:
  - plotly
  - markmap
  - glightbox
  - search
  - pdf-export:
      verbose: true
      combined: true
      media_type: print
      enabled_if_env: ENABLE_PDF_EXPORT
  - i18n:
      docs_structure: folder
      languages:
        - locale: en
          default: true
          name: English
          build: true
        - locale: hi
          name: Hindi
          build: true


markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: plotly
          class: mkdocs-plotly
          format: !!python/name:mkdocs_plotly_plugin.fences.fence_plotly
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.emoji:
      emoji_index: !!python/name:pymdownx.emoji.twemoji
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - footnotes
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - attr_list
  - md_in_html

nav:
  - Home: index.md
  - Contents: chapters/contents.md
  - 1. Computer System: chapters/chapter01.md
  - 2. Encoding Schemes and Number Systems: chapters/chapter02.md
  - 3. Emerging Trends: chapters/chapter03.md
  - 4. Problem Solving: chapters/chapter04.md
  - 5. Getting Started with Python: chapters/chapter05.md
  - 5a. Flow of Control and Functions: chapters/chapter05a.md
  - 5b. Strings and Lists: chapters/chapter05b.md
  - 5c. Tuples and Dictionary: chapters/chapter05c.md
  - 6. Societal Impacts: chapters/chapter06.md
  - 7. Suggested Practical Projects: chapters/chapter07.md
  - Question Bank: chapters/qbank.md
  - Answers to Question Bank: chapters/qbank_ans.md
  - FAQ: chapters/faq.md
